- name: Create a pmm client container
  community.docker.docker_container:
    name: pmm-client
    image: percona/pmm-client:{{ pmm_version }}
    env:
      PMM_AGENT_SERVER_ADDRESS=localhost
      PMM_AGENT_SERVER_USERNAME=admin \
      PMM_AGENT_SERVER_PASSWORD={{ pmm_admin_password }} \
      PMM_AGENT_SERVER_INSECURE_TLS=1 \
      PMM_AGENT_SETUP=1 \
      PMM_AGENT_CONFIG_FILE=config/pmm-agent.yaml \
    volumes:
      - "/etc/mysql/pmm-agent.yaml.d:/config"
    restart_policy: "always"

- name: Create pmm user in MySQL
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ admin_mysql_password }}"
    name: pmm
    password: "{{ pmm_mysql_password }}"
    priv: '*.*:ALL'
    state: present