
- name: Check pmm directory
  stat:
    path: "{{ pmm_folder }}"
  register: directory_pmm

- name: Create pmm directory if it doesn't already exist
  file:
    path: "{{ pmm_folder }}"
    state: directory
    mode: 0777
  when: not directory_pmm.stat.exists

- name: Create a pmm server container
  community.docker.docker_container:
    name: pmm-server
    image: percona/pmm-server:{{ pmm_version }}
    volumes:
      - "{{ pmm_folder }}:/srv"
    ports:
      - 443:443
    restart_policy: "always"

- name: Run a change-admin-password
  community.docker.docker_container_exec:
    container: pmm-server
    command: change-admin-password {{ pmm_admin_password }}
  register: result

- name: Make sure the grafana database is rw
  file:
    path: "{{ pmm_folder }}/grafana/grafana.db"
    state: file
    mode: 0666