
- name: Create a pmm server container
  community.docker.docker_container:
    name: pmm-server
    image: percona/pmm-server:{{ pmm_version }}
    volumes:
      - /mysql-data/pmm:/srv
    ports:
      - 443:443
    restart_policy: "always"

- name: Run a change-admin-password
  community.docker.docker_container_exec:
    container: pmm-server
    command: change-admin-password {{ pmm_admin_password }}
  register: result
