## Create users 
- name: Create pmm user in MySQL
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ admin_mysql_password }}"
    name: "{{ admin_mysql_user }}"
    password: "{{ admin_mysql_password }}"
    priv: '*.*:ALL'
    state: present